Repository sarahlane8/Rancid_Tomatillos, pull requests merged in 2021-05, with the labels that each got.

#25 Feature/display movies
  public/index.html
  src/components/App/App.js
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
  src/components/Movies/Movies.css
  src/components/Movies/Movies.js
  src/index.js
  src/movieData.js
Labels: iteration 1, user stories

#27 Feature/display movie details
  src/components/App/App.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/components/Movies/Movies.js
Labels: React, iteration 2, user stories

#29 Feature/api calls
  src/apiCalls.js
  src/components/App/App.js
  src/components/MovieDetails/MovieDetails.js
Labels: React, iteration 3, refactor, user stories

#33 Feature/cleaning function
  package-lock.json
  src/components/App/App.js
  src/components/MovieDetails/MovieDetails.js
  src/utilities.js
Labels: React, enhancement

#34 Feature/nav bar
  src/components/App/App.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
Labels: React, enhancement

#36 Feature/nav bar
  src/components/App/App.js
  src/components/NavBar/NavBar.js
Labels: React, enhancement

#37 Feature/install cypress
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/cypress.json
  cypress/integration/cypress/fixtures/example.json
  cypress/integration/cypress/integration/examples/actions.spec.js
  cypress/integration/cypress/integration/examples/aliasing.spec.js
  cypress/integration/cypress/integration/examples/assertions.spec.js
  cypress/integration/cypress/integration/examples/connectors.spec.js
  cypress/integration/cypress/integration/examples/cookies.spec.js
  cypress/integration/cypress/integration/examples/cypress_api.spec.js
  cypress/integration/cypress/integration/examples/files.spec.js
  cypress/integration/cypress/integration/examples/local_storage.spec.js
  cypress/integration/cypress/integration/examples/location.spec.js
  cypress/integration/cypress/integration/examples/misc.spec.js
  cypress/integration/cypress/integration/examples/navigation.spec.js
  cypress/integration/cypress/integration/examples/network_requests.spec.js
  cypress/integration/cypress/integration/examples/querying.spec.js
  cypress/integration/cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/cypress/integration/examples/traversal.spec.js
  cypress/integration/cypress/integration/examples/utilities.spec.js
  cypress/integration/cypress/integration/examples/viewport.spec.js
  cypress/integration/cypress/integration/examples/waiting.spec.js
  cypress/integration/cypress/integration/examples/window.spec.js
  cypress/integration/cypress/plugins/index.js
  cypress/integration/cypress/support/commands.js
  cypress/integration/cypress/support/index.js
  cypress/integration/homepage_spec.js
  cypress/integration/movie_details_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: Cypress, enhancement

#42 Add redirect to homepage
  src/components/App/App.js
Labels: React Router, refactor

#43 Feature/redirect
  src/components/App/App.js
  src/components/MovieDetails/MovieDetails.js
  src/components/NoMatch/NoMatch.css
  src/components/NoMatch/NoMatch.js
Labels: refactor

#44 Fix bug on back button
  src/components/App/App.js
  src/components/MovieDetails/MovieDetails.js
Labels: refactor

#46 Feature/refactor cypress
  cypress/integration/homepage_spec.js
  cypress/integration/movie_details_spec.js
  package-lock.json
  src/components/App/App.js
  src/components/Form/Form.js
  src/components/MovieDetails/MovieDetails.js
  src/components/Movies/Movies.css
Labels: Cypress, user stories

#47 Refactoring
  src/components/App/App.js
  src/components/Form/Form.css
  src/components/Form/Form.js
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
  src/components/Movies/Movies.css
  src/components/NavBar/NavBar.css
  src/components/NoMatch/NoMatch.css
  src/components/NoMatch/NoMatch.js
Labels: CSS, refactor

#48 Feature/css
  src/components/MovieCard/MovieCard.css
  src/components/MovieCard/MovieCard.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/components/NavBar/NavBar.css
  src/utilities.js
Labels: CSS

#51 Refactor/final cleanup
  cypress/integration/homepage_spec.js
  cypress/integration/movie_details_spec.js
  src/apiCalls.js
  src/components/MovieCard/MovieCard.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/components/Movies/Movies.js
  src/components/NavBar/NavBar.css
  src/index.js
Labels: CSS, Cypress, React, refactor
